### ISSUE TITLE
 InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.1 when using version 1.4.2.

### ISSUE THREAD

**Issue by Arham-12336** [onurkya7/AudioDeepFakeDetection#1]
I am trying to run main.py. And when uploading the fake file from the test folder. I am getting this error. 

```
InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.0.1 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python\Python\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Python\Python\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Users\ArhamShams\Desktop\AudioDeepFakeDetection\main.py", line 25, in run
    result = function(dir)
             ^^^^^^^^^^^^^
  File "C:\Users\ArhamShams\Desktop\AudioDeepFakeDetection\test.py", line 10, in runtest
    loaded_model = joblib.load("models/random_forest_model.joblib")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python\Lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python\Lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "C:\Python\Python\Lib\pickle.py", line 1205, in load
    dispatch[key[0]](self)
  File "C:\Python\Python\Lib\site-packages\joblib\numpy_pickle.py", line 402, in load_build
    Unpickler.load_build(self)
  File "C:\Python\Python\Lib\pickle.py", line 1710, in load_build
    setstate(state)
  File "sklearn\\tree\\_tree.pyx", line 865, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn\\tree\\_tree.pyx", line 1571, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
```

**Comment by kaworururur** [comment]
same error :( if you will find the problem can you help me too?

**Comment by Arham-12336** [comment]
So the issue is with the joblib version. Here is what you can do to resolve this issue

1. pip install joblib
2. Run the train.py. Make sure you save the model with a new name.
3. After that update the model name in the test.py
4. Then run the main.py and you are good to go

**Comment by Arham-12336** [comment]
So the issue is with the joblib version. Here is what you can do to resolve this issue

pip install joblib
Run the train.py. Make sure you save the model with a new name.
After that update the model name in the test.py
Then run the main.py and you are good to go

**Comment by kaworururur** [comment]
thank you! actually, it doesnt work on my own files, maybe you know, can i fix it somehow?
